version: '2'

services:
  server:
    image: golang:1.15
    restart: always
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
    volumes:
    - ./src:/app
    - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: go run main.go
  cassandra:
    image: docker.io/bitnami/cassandra:3-debian-10
    ports:
      - 7000:7000
      - 9042:9042
    volumes:
      - cassandra_data:/bitnami
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
volumes:
  cassandra_data:
    driver: local
